replicaCount: 1
postgres:
  host: "192.168.18.205"
  port: 5432
  database: "fhir"
  credentialsSecret:
    name: fhir-db-secret
    usernameKey: "postgresql"
    passwordKey: "mverastegui2025"
ingress:
  enabled: true
  hosts:
    - host: ayamjuthapi.prueba.pe
      paths:
        - path: /
          pathType: Prefix
  tls: []