alertmanager:
  enabled: true
  config:
    receivers:
      - name: sre-team
        email_configs:
          - to: alerts@prueba.pe
ingress:
  enabled: true
  hosts:
    - host: ayamjutmonitor.prueba.pe
      paths:
        - path: /
          pathType: Prefix
  tls: []