---
- name: Configurar Infraestructura de Kubernetes
  hosts: all
  become: yes
  tasks:
    - name: Instalar Kubernetes Cluster
      import_tasks: roles/k8s/tasks/install_kubernetes.yaml

- name: Desplegar Ingress Controller (solo en Master)
  hosts: master
  become: yes
  import_tasks: roles/k8s/tasks/deploy_ingress.yaml

- name: Desplegar Servicios (solo en Master)
  hosts: master
  become: yes
  tasks:
    - import_tasks: roles/k8s/tasks/deploy_keycloak.yaml
    - import_tasks: roles/k8s/tasks/deploy_fhir_server.yaml
    - import_tasks: roles/k8s/tasks/deploy_fhir_gateway.yaml
    - import_tasks: roles/k8s/tasks/deploy_prometheus.yaml
    - import_tasks: roles/k8s/tasks/deploy_graylog.yaml
    - import_tasks: roles/k8s/tasks/deploy_fluentbit.yaml
    - import_tasks: roles/k8s/tasks/deploy_grafana.yaml