- name: Desplegar Ingress Controller (NGINX)
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_repo_url: https://kubernetes.github.io/ingress-nginx
    chart_version: "4.11.3"
    release_namespace: default
    values_files:
      - roles/k8s/templates/ingress-nginx-values.yaml