- name: Desplegar Prometheus
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    chart_repo_url: https://prometheus-community.github.io/helm-charts
    chart_version: "15.0.0"
    release_namespace: monitoring
    values_files:
      - roles/k8s/templates/prometheus-values.yaml