- name: Desplegar Graylog
  kubernetes.core.helm:
    name: graylog
    chart_ref: kongz/graylog
    chart_repo_url: https://charts.kong-z.com
    chart_version: "2.3.2"
    release_namespace: logging
    values_files:
      - roles/k8s/templates/graylog-values.yaml